# Generated by Django 4.2.1 on 2023-05-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('start_time', models.DurationField()),
                ('end_time', models.DurationField()),
                ('text', models.TextField()),
            ],
        ),
    ]
