# Generated by Django 4.2.1 on 2023-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoSubtitle', '0002_remove_subtitle_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='text',
            field=models.TextField(default='none'),
        ),
    ]
