# Generated by Django 4.2.1 on 2023-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoSubtitle', '0004_alter_subtitle_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
