# Generated by Django 4.2.1 on 2023-05-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoSubtitle', '0005_alter_subtitle_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtitle',
        ),
    ]
